test("array pagination", () => {
  const data = [
    {
      id: "1417",
      attributes: {
        index: 1,
        name: "Cumi-cumi ninja33",
        summary: "1kg/pack",
        description: "Halo",
        price: 1000,
        priceBeforeDiscount: 49000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/cara_mendapatkan_review_baik_010e3632fa.png",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: false,
        isQuantityUnit: true,
        quantityUnit: "gram",
        addOns: [
          {
            category: "qweasd",
            description: null,
            isRequired: false,
            type: "RADIO",
            minOptions: 1,
            maxOptions: null,
            options: [
              {
                label: "coklat",
                price: 0,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
        ],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "1425",
      attributes: {
        index: 2,
        name: "Oppa Korea",
        summary: "Oppa Korea Lawannya BTS",
        description: "",
        price: 90000,
        priceBeforeDiscount: 280000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/1_m_O_Qxwb_Xg_AJF_5_S_Ti_I15_Xb7_A_64341d28ab.jpeg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: true,
        isQuantityUnit: false,
        quantityUnit: "gram",
        addOns: [
          {
            category: "Topping",
            description: "Ok",
            isRequired: true,
            type: "RADIO",
            minOptions: 1,
            maxOptions: 1,
            options: [
              {
                label: "Topping 1",
                price: 3000,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Topping 2",
                price: 5000,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
        ],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "1424",
      attributes: {
        index: 3,
        name: "Sokovia Beef",
        summary: "Hohoho",
        description: "",
        price: 0,
        priceBeforeDiscount: 0,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/image_format_comparison_webp_jpg_png_9fbc99c710.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "1419",
      attributes: {
        index: 4,
        name: "Daging Sapi Luar Angkasa",
        summary: "Omamen",
        description: "Ini deskripsi\n\nAda new line",
        price: 88000,
        priceBeforeDiscount: 100000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/image_format_comparison_webp_jpg_png_9fbc99c710.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "1418",
      attributes: {
        index: 5,
        name: "Ayam Kekinian",
        summary: "Ayam ya ayam",
        description:
          "ayam tidak pernah seenak ini\n\n Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint est explicabo eaque dolorem magnam, reiciendis et! Porro consectetur, doloribus aspernatur voluptatum laborum natus pariatur numquam sed eius et! Eligendi, quod.\n                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint est explicabo eaque dolorem magnam, reiciendis et! Porro consectetur, doloribus aspernatur voluptatum laborum natus pariatur numquam sed eius et! Eligendi, quod.\n                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint est explicabo eaque dolorem magnam, reiciendis et! Porro consectetur, doloribus aspernatur voluptatum laborum natus pariatur numquam sed eius et! Eligendi, quod.\n                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint est explicabo eaque dolorem magnam, reiciendis et! Porro consectetur, doloribus aspernatur voluptatum laborum natus pariatur numquam sed eius et! Eligendi, quod.\n                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint est explicabo eaque dolorem magnam, reiciendis et! Porro consectetur, doloribus aspernatur voluptatum laborum natus pariatur numquam sed eius et! Eligendi, quod.\n                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint est explicabo eaque dolorem magnam, reiciendis et! Porro consectetur, doloribus aspernatur voluptatum laborum natus pariatur numquam sed eius et! Eligendi, quod.",
        price: 89000,
        priceBeforeDiscount: 0,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://i.postimg.cc/L82wNx0Q/Whats-App-Image-2021-03-16-at-17-14-38.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "1420",
      attributes: {
        index: 6,
        name: "Chicken Antariksa2",
        summary: "Ayamayaman2",
        description: "ayam dari bulan",
        price: 190000,
        priceBeforeDiscount: 0,
        isAvailable: true,
        isDisplayed: true,
        sku: "SKU123",
        category: {
          data: {
            id: "318",
            attributes: {
              title: "abaca",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/image_format_comparison_webp_jpg_png_9fbc99c710.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: true,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [
          {
            category: "Topping Aja",
            description: "Pilih topping yg kamu suka",
            isRequired: true,
            type: "CHECKBOX",
            minOptions: 1,
            maxOptions: 1,
            options: [
              {
                label: "Cokelat",
                price: 1,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Strawberry",
                price: 0,
                isAvailable: false,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Durian",
                price: 1000,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
          {
            category: "Sambal",
            description: null,
            isRequired: true,
            type: "RADIO",
            minOptions: 1,
            maxOptions: 1,
            options: [
              {
                label: "Sambal Bawang",
                price: 0,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Sambal Balado",
                price: 0,
                isAvailable: false,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
        ],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "1423",
      attributes: {
        index: 7,
        name: "Cumi-cumi Antariksa",
        summary: "",
        description: "",
        price: 87000,
        priceBeforeDiscount: 100000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "1422",
      attributes: {
        index: 8,
        name: "Daging Berkah Abadi",
        summary: "Dagingku",
        description: "",
        price: 999000,
        priceBeforeDiscount: 1000000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "318",
            attributes: {
              title: "abaca",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: true,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "2617",
      attributes: {
        index: 15,
        name: "Martabak (Addons) ganti gambar",
        summary: "",
        description: "Martabak enak banget!",
        price: 35000,
        priceBeforeDiscount: 50000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/tara_clark_Gk8_LG_7ds_HWA_unsplash_98a517401a.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: true,
        isQuantityUnit: false,
        quantityUnit: "kg",
        addOns: [
          {
            category: "Topping",
            description: null,
            isRequired: true,
            type: "CHECKBOX",
            minOptions: 1,
            maxOptions: 2,
            options: [
              {
                label: "Keju",
                price: 5000,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Kacang",
                price: 2500,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Coklat",
                price: 3000,
                isAvailable: false,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
          {
            category: "Pinggiran",
            description: null,
            isRequired: true,
            type: "RADIO",
            minOptions: 1,
            maxOptions: 1,
            options: [
              {
                label: "Tipis",
                price: 0,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Tebal Keju",
                price: 6000,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Tebal Coklat",
                price: 4000,
                isAvailable: false,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
          {
            category: "Saos",
            description: null,
            isRequired: true,
            type: "CHECKBOX",
            minOptions: 1,
            maxOptions: 2,
            options: [
              {
                label: "Sambal Pedas",
                price: 5000,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Tomat",
                price: 2500,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
          {
            category: "Bonus",
            description: null,
            isRequired: true,
            type: "CHECKBOX",
            minOptions: null,
            maxOptions: null,
            options: [
              {
                label: "Kertas Kado",
                price: 0,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
              {
                label: "Kertas Minyak",
                price: 0,
                isAvailable: true,
                __typename: "ComponentProductAddOnOptions",
              },
            ],
            __typename: "ComponentProductAddOns",
          },
        ],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "2618",
      attributes: {
        index: 16,
        name: "14",
        summary: "",
        description: "",
        price: 1414,
        priceBeforeDiscount: 100000000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: {
            id: "317",
            attributes: {
              title: "OK",
              __typename: "Category",
            },
            __typename: "CategoryEntity",
          },
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "2619",
      attributes: {
        index: 17,
        name: "15",
        summary: "",
        description: "",
        price: 1515,
        priceBeforeDiscount: 100000000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "2620",
      attributes: {
        index: 18,
        name: "16",
        summary: "",
        description: "",
        price: 1616,
        priceBeforeDiscount: 100000000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "2621",
      attributes: {
        index: 19,
        name: "17",
        summary: "",
        description: "",
        price: 1717,
        priceBeforeDiscount: 100000000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "2622",
      attributes: {
        index: 20,
        name: "18",
        summary: "",
        description: "",
        price: 1818,
        priceBeforeDiscount: 100000000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "2623",
      attributes: {
        index: 21,
        name: "19",
        summary: "",
        description: "",
        price: 1919,
        priceBeforeDiscount: 100000000,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/Group_88174bfa17.png",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "4833",
      attributes: {
        index: 30,
        name: "Keripik Syaiton",
        summary: "Keripik Mantap Rasa Syaiton",
        description: "Keren",
        price: 0,
        priceBeforeDiscount: 0,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/272307181_915204809144722_2415315274166851358_n_b382d6ac46_6b9ebc3555.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "4837",
      attributes: {
        index: 31,
        name: "Paket Buah dan Coklat (edit)",
        summary: "Buah - buahan dan Coklat",
        description: "Buah - buahan dan Coklat",
        price: 100000,
        priceBeforeDiscount: 0,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/nrd_D6_Tu_L3ch_LE_unsplash_6d6101517a.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "4838",
      attributes: {
        index: 32,
        name: "Faisal Test",
        summary: "",
        description: "",
        price: 22222,
        priceBeforeDiscount: 33333,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/Seek_Png_com_bruh_png_2316626_85fb6bc8a9.png",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "4869",
      attributes: {
        index: 33,
        name: "test tanpa kategori (edit)",
        summary: "test",
        description: "test",
        price: 42342,
        priceBeforeDiscount: 0,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: null,
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "4870",
      attributes: {
        index: 34,
        name: "Coba 2",
        summary: "",
        description: "",
        price: 10000,
        priceBeforeDiscount: 0,
        isAvailable: true,
        isDisplayed: true,
        sku: "",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: null,
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
    {
      id: "4873",
      attributes: {
        index: 35,
        name: "Cake Slice Coklat 2",
        summary: "1 pcs",
        description: "rasa enak",
        price: 12000,
        priceBeforeDiscount: 13000,
        isAvailable: true,
        isDisplayed: true,
        sku: "441231",
        category: {
          data: null,
          __typename: "CategoryEntityResponse",
        },
        image: {
          data: {
            attributes: {
              url: "https://orderdulu-dev.s3.ap-southeast-1.amazonaws.com/pexels_elli_1854652_Custom_bdf74ac579.jpg",
              __typename: "UploadFile",
            },
            __typename: "UploadFileEntity",
          },
          __typename: "UploadFileEntityResponse",
        },
        isAddOnsEnabled: null,
        isQuantityUnit: false,
        quantityUnit: "",
        addOns: [],
        __typename: "Product",
      },
      __typename: "ProductEntity",
    },
  ];

  const paginate = (data, pageSize, pageNumber) => {
    return [...data].slice((pageNumber - 1) * pageSize, pageNumber * pageSize);
  };
  console.log("data > ", paginate(data, 10, 1));
});
